#-- coding: utf-8 --
from . import contact_form
from . import product_form
from . import order_lines
from . import product_form_purchase
from . import product_form_sale
from . import product_pricelist
from . import product_pricelist_pricerules
from . import purchase_order
from . import web_general
from . import purchase_order_lines